# Generated by Django 4.2.7 on 2023-11-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_email', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
